In [1]:
!nvidia-smi

Sun Oct 24 00:21:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
#Mount Drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
%cd /content/gdrive/MyDrive/style-transfer-research/Pytorch_AdaIN
!ls

/content/gdrive/MyDrive/style-transfer-research/Pytorch_AdaIN
AdaIN-test.ipynb
blonde_girl_mondrian.jpg
blonde_girl_mondrian_style_transfer_demo.jpg
blonde_girl_mondrian_with_style_image.jpg
_config.yml
content
content_train
dataset.py
download_coco.sh
fuse_model.py
fusion.py
golden_gate_hosi.jpg
golden_gate_hosi_style_transfer_demo.jpg
golden_gate_hosi_with_style_image.jpg
LICENSE
model.py
model_vgg_first_layers.pth
neko_sketch.jpg
neko_sketch_style_transfer_demo.jpg
neko_sketch_with_style_image.jpg
__pycache__
README.md
res
resout_gif
result
result_mycat
result_new
result_rolling_fusion
style
style_train
style_train_resized
test.py
train.py


In [12]:
!python test.py --content /content/gdrive/MyDrive/style-transfer-research/SAFIN/input/content/257098.jpg --style /content/gdrive/MyDrive/style-transfer-research/SAFIN/input/style/contrast_of_forms.jpg --model_state_path model_vgg_first_layers.pth

# CUDA available: Tesla P100-PCIE-16GB
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
result saved into files starting with 257098_contrast_of_forms


In [ ]:
# !bash download_coco.sh

Streaming output truncated to the last 5000 lines.
 extracting: train2017/000000259556.jpg  
 extracting: train2017/000000381931.jpg  
 extracting: train2017/000000569592.jpg  
 extracting: train2017/000000229396.jpg  
 extracting: train2017/000000488990.jpg  
 extracting: train2017/000000348684.jpg  
 extracting: train2017/000000234031.jpg  
 extracting: train2017/000000563584.jpg  
 extracting: train2017/000000276069.jpg  
 extracting: train2017/000000401194.jpg  
 extracting: train2017/000000502089.jpg  
 extracting: train2017/000000192183.jpg  
 extracting: train2017/000000425127.jpg  
 extracting: train2017/000000126766.jpg  
 extracting: train2017/000000324161.jpg  
 extracting: train2017/000000452746.jpg  
 extracting: train2017/000000423782.jpg  
 extracting: train2017/000000546343.jpg  
 extracting: train2017/000000249290.jpg  
 extracting: train2017/000000025529.jpg  
 extracting: train2017/000000316928.jpg  
 extracting: train2017/000000337866.jpg  
 extracting: train2017/00

In [ ]:
import os
# print(len(os.listdir('content_train/train2017')))
print(len(os.listdir('content_train/train2017_resized')))
try:
    print(len(os.listdir('content_train/img')))
except:
    pass
print(len(os.listdir('style_train')))
print(len(os.listdir('style_train_resized')))

OSError: ignored

In [ ]:
%%bash
cd /content/gdrive/MyDrive/style-transfer-research/Pytorch_AdaIN/style_train
# unzip train_9.zip
# rm train_9.zip
# cd ..

In [ ]:
from torchvision.models import vgg19

In [ ]:
vgg = vgg19(pretrained=True)
print(vgg)

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padd

In [ ]:
from tensorflow.keras.applications.vgg19 import VGG19
vgg_tf = VGG19(include_top = True, weights = 'imagenet')
vgg_tf.summary()

574717952/574710816 [==============================] - 5s 0us/step
Model: "vgg19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
____________________________________________________________

In [ ]:
import shutil
import os
for name in os.listdir("content_train/train2017")[79433:]:
    shutil.move("content_train/train2017/{}".format(name), "content_train/img/")

In [ ]:
!python train.py --train_content_dir content_train/train2017 --train_style_dir style_train --test_content_dir content_train/train2017 --test_style_dir style_train --batch_size 32 

# CUDA available: Tesla P100-PCIE-16GB
# Minibatch-size: 32
# epoch: 20

Length of train image pairs: 53405
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth
100% 548M/548M [00:06<00:00, 90.1MB/s]
Start 1 epoch
0it [00:00, ?it/s][1/total 20 epoch],[1 /total 1669 iteration]: 188.54966735839844
1it [00:45, 45.00s/it][1/total 20 epoch],[2 /total 1669 iteration]: 174.903076171875
2it [01:28, 43.97s/it][1/total 20 epoch],[3 /total 1669 iteration]: 185.6387481689453
3it [02:12, 43.99s/it][1/total 20 epoch],[4 /total 1669 iteration]: 193.73255920410156
4it [02:55, 43.67s/it][1/total 20 epoch],[5 /total 1669 iteration]: 169.02691650390625
5it [03:38, 43.40s/it][1/total 20 epoch],[6 /total 1669 iteration]: 153.6666259765625
6it [04:21, 43.29s/it][1/total 20 epoch],[7 /total 1669 iteration]: 222.13589477539062
7it [05:04, 43.24s/it][1/total 20 epoch],[8 /total 1669 iteration]: 178.1804962158203
8it [05:47, 43.17s/it][1/

In [ ]:
# import torch
# x = torch.zeros(1, 1, 4, 4)
# x[:, :, 3] = 1.

# x90 = x.transpose(2, 3)
# x180 = x.flip(2)
# x270 = x.transpose(2, 3).flip(3)

# print(x)
# print(x90)
# print(x180)
# print(x270)


tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [1., 1., 1., 1.]]]])
tensor([[[[0., 0., 0., 1.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.]]]])
tensor([[[[1., 1., 1., 1.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])
tensor([[[[1., 0., 0., 0.],
          [1., 0., 0., 0.],
          [1., 0., 0., 0.],
          [1., 0., 0., 0.]]]])


In [ ]:
# from scipy import ndimage
# def rotate(inputs, x):
#     return ndimage.rotate(inputs, x, reshape=False)

In [ ]:
# import torchvision.transforms.functional as TF
# import random

# class MyRotationTransform:
#     """Rotate by one of the given angles."""

#     def __init__(self, angles):
#         self.angles = angles

#     def __call__(self, x):
#         return TF.rotate(x, self.angles, center = [2,0,0,0], expand = False)

# rotation_transform_45 = MyRotationTransform(angles=45)
# rotation_transform_60 = MyRotationTransform(angles=60)
# rotation_transform_75 = MyRotationTransform(angles=75)

In [ ]:
# rotation_transform_45(x)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 1.]]]])